<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="pramit" failures="1" tests="6" name="rahulshettyacademyShopping.website.Tests.StandAloneTest" time="16.869" errors="0" timestamp="2024-02-20T13:56:43 IST" skipped="1">
  <testcase classname="rahulshettyacademyShopping.website.Tests.StandAloneTest" name="orderHistry" time="2.280"/>
  <testcase classname="rahulshettyacademyShopping.website.Tests.StandAloneTest" name="failTest" time="0.023">
    <skipped/>
  </testcase> <!-- failTest -->
  <testcase classname="rahulshettyacademyShopping.website.Tests.StandAloneTest" name="submitOrder" time="2.091"/>
  <testcase classname="rahulshettyacademyShopping.website.Tests.StandAloneTest" name="failTest" time="0.001">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at org.testng.Assert.assertTrue(Assert.java:67)
at rahulshettyacademyShopping.website.Tests.StandAloneTest.failTest(StandAloneTest.java:87)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
    </failure>
  </testcase> <!-- failTest -->
  <testcase classname="rahulshettyacademyShopping.website.Tests.StandAloneTest" name="submitOrder" time="9.655"/>
  <testcase classname="rahulshettyacademyShopping.website.Tests.StandAloneTest" name="orderHistry" time="2.819"/>
</testsuite> <!-- rahulshettyacademyShopping.website.Tests.StandAloneTest -->
